server:
  port: 8080

spring:
  application:
    name: DEPARTMENT-SERVICE
  boot:
    message: Hello, Department Service! UPDATED

  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
